In [2]:
# preprocessing : IN ml preprocessing means preparing raw data before giving it to a machine learning model .

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame({
    "Name" : ["user1","user2", "user3"],
    "Gender" : ["Male", "Female", "Male"],
    "Age" : [21,23, 22]
})
df

    Name  Gender  Age
0  user1    Male   21
1  user2  Female   23
2  user3    Male   22

In [5]:
# label encoding  : converts categorical values into numerical 
from sklearn.preprocessing import LabelEncoder

In [6]:
encoder = LabelEncoder()

In [7]:
df["Gender_status"] = encoder.fit_transform(df["Gender"])

In [8]:
df

    Name  Gender  Age  Gender_status
0  user1    Male   21              1
1  user2  Female   23              0
2  user3    Male   22              1

In [9]:
# one-hot encoding :
# One-Hot Encoding is a data preprocessing technique that converts categorical (text) data into separate columns containing 0 and 1
df["City"] = ["Mumbai", "Surat", "Ahmedabad"]

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
encoder = OneHotEncoder(sparse_output=False)

status = encoder.fit_transform(df[["City"]])
status

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [12]:
status

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [ ]:
# status — contains the encoded numerical values produced by your encoder.

# columns=encoder.get_feature_names_out(["City"]) — gets the output column names from the encoder, such as City_Ahmedabad, City_Mumbai, and City_Surat.

# index=df.index — uses the same row index as your original DataFrame.

In [13]:
# We use this code in ML preprocessing to add One-Hot Encoded columns to our original dataset
encoded_df = pd.DataFrame(
    status,
    columns=encoder.get_feature_names_out(["City"]),
    index=df.index
)

df = pd.concat([df, encoded_df], axis=1)

df

,Name,Gender,Age,Gender_status,City,City_Ahmedabad,City_Mumbai,City_Surat
0,user1,Male,21,1,Mumbai,0.0,1.0,0.0
1,user2,Female,23,0,Surat,0.0,0.0,1.0
2,user3,Male,22,1,Ahmedabad,1.0,0.0,0.0

In [2]:
# feature scalling  : bring numerical features to comparable scales  : knn , svm d

# Scaling means converting numerical values into a similar range so that features with
# large numbers do not unfairly dominate features with small numbers.

In [ ]:
# KNN and SVM are two supervised machine learning algorithms. Both learn from labelled training data, but they make predictions in different ways.

# KNN (K-Nearest Neighbors) knn by nearest distance
# d = sqrt((x2 - x1)^2 + (y2 - y1)^2)
# SVM = Support Vector Machine

In [15]:
df = pd.DataFrame({
    "Age" : [23, 24, 27, 40],
    "Salary" : [20000, 23000, 26000, 100000]
})
df

   Age  Salary
0   23   20000
1   24   23000
2   27   26000
3   40  100000

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()
df[["Age", "Salary"]] = scaler.fit_transform(df[["Age", "Salary"]])
df

        Age    Salary
0 -0.808736 -0.665980
1 -0.661693 -0.576185
2 -0.220564 -0.486390
3  1.690994  1.728556

In [18]:
# MinMax : 0 to 1 :  x` = (x - xmin)/(xmax - xmin)

In [ ]:
# You are understanding it correctly. KNN and SVM are ML algorithms (methods), while MinMaxScaler and StandardScaler are preprocessing tools.

In [1]:
# minmaxscaler

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Dataset
df = pd.DataFrame({
    "Age": [20, 30, 40, 50],
    "Salary": [10000, 20000, 30000, 40000]
})

print("Original Data:")
print(df)

# Apply MinMaxScaler
scaler = MinMaxScaler()

df[["Age", "Salary"]] = scaler.fit_transform(
    df[["Age", "Salary"]]
)

print("\nScaled Data:")
print(df.round(2))

Original Data:
   Age  Salary
0   20   10000
1   30   20000
2   40   30000
3   50   40000

Scaled Data:
    Age  Salary
0  0.00    0.00
1  0.33    0.33
2  0.67    0.67
3  1.00    1.00

In [2]:
# Standard scaler

In [2]:

import pandas as pd
from sklearn.preprocessing import StandardScaler

# Dataset
df = pd.DataFrame({
    "Age": [20, 30, 40, 50],
    "Salary": [10000, 20000, 30000, 40000]
})

print("Original Data:")
print(df)

# Apply StandardScaler
scaler = StandardScaler()

df[["Age", "Salary"]] = scaler.fit_transform(
    df[["Age", "Salary"]]
)

print("\nStandardized Data:")
print(df.round(2))

Original Data:
   Age  Salary
0   20   10000
1   30   20000
2   40   30000
3   50   40000

Standardized Data:
    Age  Salary
0 -1.34   -1.34
1 -0.45   -0.45
2  0.45    0.45
3  1.34    1.34

In [5]:
# give me re mydata after stndard scaler 

import pandas as pd
from sklearn.preprocessing import StandardScaler

# Original data
df = pd.DataFrame({
    "Age": [20, 25, 30, 35, 40],
    "Salary": [20000, 30000, 40000, 50000, 60000]
})

# Create scaler
scaler = StandardScaler()

# Scale the data
scaled_data = scaler.fit_transform(df[["Age", "Salary"]])

# Convert scaled data into DataFrame
scaled_df = pd.DataFrame(
    scaled_data,
    columns=["Age", "Salary"]
)

print("Scaled Data:")
print(scaled_df.round(2))

# Get original values back
original_data = scaler.inverse_transform(scaled_data)

# Convert original values into DataFrame
original_df = pd.DataFrame(
    original_data,
    columns=["Age", "Salary"]
)

print("\nOriginal Age and Salary:")
print(original_df)

Scaled Data:
    Age  Salary
0 -1.41   -1.41
1 -0.71   -0.71
2  0.00    0.00
3  0.71    0.71
4  1.41    1.41

Original Age and Salary:
    Age   Salary
0  20.0  20000.0
1  25.0  30000.0
2  30.0  40000.0
3  35.0  50000.0
4  40.0  60000.0

In [ ]:
import pandas as pd
from sklearn.model_linear import LinearRegression
from sklearn.selection