In [75]:
# linear regerssion 

# | Code | Explanation |
# |---|---|
# | `import pandas as pd` | Imports Pandas to store and work with tabular data. |
# | `train_test_split` | Splits data into training and testing sets. |
# | `LinearRegression` | Creates a model that learns a linear relationship between inputs and outputs. |
# | `mean_absolute_error` | Measures the average absolute prediction error. |
# | `r2_score` | Measures how well predictions explain the variation in actual values. |

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

df = pd.DataFrame({
    
    "StudyHours": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Score": [15, 25, 35, 40, 50, 60, 65, 75, 85, 95]
})

df

   StudyHours  Score
0           1     15
1           2     25
2           3     35
3           4     40
4           5     50
5           6     60
6           7     65
7           8     75
8           9     85
9          10     95

In [76]:
# Separate X and y

# Double brackets return a DataFrame with two-dimensional structure, which scikit-learn expects for features. By contrast:

X = df[["StudyHours"]]
y = df["Score"]

print("Features (X):")
display(X)

print("Target (y):")
display(y)

Features (X):

   StudyHours
0           1
1           2
2           3
3           4
4           5
5           6
6           7
7           8
8           9
9          10

Target (y):

0    15
1    25
2    35
3    40
4    50
5    60
6    65
7    75
8    85
9    95
Name: Score, dtype: int64

In [77]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2 , random_state=42
    # , random_state=42
)

print("Training rows:", (X_train))
print("Testing rows:", (X_test))

Training rows:    StudyHours
5           6
0           1
7           8
2           3
9          10
4           5
3           4
6           7
Testing rows:    StudyHours
8           9
1           2

In [78]:
# train model
model = LinearRegression()
model.fit(X_train,y_train)
new_data = pd.DataFrame({
    'StudyHours': [11]
})
predict = model.predict([[11]])
predict = model.predict(new_data)
print(predict)

model.predict(pd.DataFrame({
    'StudyHours':[11]
}))
# predict = model.predict([[]])
# df["Predicted_Score"] = model.predict(df[["StudyHours"]])

# print(df)
print(df)
print(predict)
print(new_data)

[102.02586207]
   StudyHours  Score
0           1     15
1           2     25
2           3     35
3           4     40
4           5     50
5           6     60
6           7     65
7           8     75
8           9     85
9          10     95
[102.02586207]
   StudyHours
0          11

C:\Users\prini\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [79]:
# Create new data
new_data = pd.DataFrame({
    "StudyHours": [11]
})

# Predict score
prediction = model.predict(new_data)

# Add predicted data to original dataset
new_data["Score"] = prediction.round(2)

df = pd.concat([df, new_data], ignore_index=True)

# Display updated dataset
df

    StudyHours   Score
0            1   15.00
1            2   25.00
2            3   35.00
3            4   40.00
4            5   50.00
5            6   60.00
6            7   65.00
7            8   75.00
8            9   85.00
9           10   95.00
10          11  102.03

In [3]:

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# 1. Create the dataset
df = pd.DataFrame({
    "StudyHours": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Score": [15, 25, 35, 40, 50, 60, 65, 75, 85, 95]
})

# 2. Separate input (X) and output (y)
X = df[["StudyHours"]]
y = df["Score"]

# 3. Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Create the Linear Regression model
model = LinearRegression()

# 5. Train the model
model.fit(X_train, y_train)

# 6. Predict scores for test data
y_pred = model.predict(X_test)
# print(y_pred)

results = pd.DataFrame({
    "StudyHours": X_test["StudyHours"].values,
    "ActualScore": y_test.values,
    "PredictedScore": y_pred.round(2)
})

display(results)

[84.69827586 24.05172414]

   StudyHours  ActualScore  PredictedScore
0           9           85           84.70
1           2           25           24.05

In [2]:
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score , mean_absolute_error

df = pd.DataFrame({
    "studyhours":[3,4,5,6,7,8,9],
    "marks":[45,56,67,78,89,90,94]
})
df

   studyhours  marks
0           3     45
1           4     56
2           5     67
3           6     78
4           7     89
5           8     90
6           9     94

In [3]:
x = df[["studyhours"]]
y = df["marks"]
x , y

(   studyhours
 0           3
 1           4
 2           5
 3           6
 4           7
 5           8
 6           9,
 0    45
 1    56
 2    67
 3    78
 4    89
 5    90
 6    94
 Name: marks, dtype: int64)

In [4]:
x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=42
)
print(x_train)
print(x_test)

   studyhours
5           8
2           5
4           7
3           6
6           9
   studyhours
0           3
1           4

In [5]:
model = LinearRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

print(y_pred)

[57.2 63.8]

In [10]:
result = pd.DataFrame({
    "studenthours":x_test["studyhours"].values,
    "actusalmarks":y_test.values,
    "predictionmarks":y_pred.round(2)
})
print(result)

   studenthours  actusalmarks  predictionmarks
0             3            45             57.2
1             4            56             63.8

In [11]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

In [12]:
# %pip install pandas scikit-learn

Requirement already satisfied: pandas in C:\Users\prini\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: scikit-learn in C:\Users\prini\anaconda3\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\prini\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\prini\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\prini\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\prini\anaconda3\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\prini\anaconda3\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\prini\anaconda3\Lib\site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\prini\anaconda3\Lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in C:\Users\prini\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [62]:
df = pd.DataFrame({
    "StudyHours": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Attendance": [50, 55, 60, 65, 70, 75, 80, 85, 90, 95],
    "AssignmentMarks": [40, 45, 50, 55, 60, 65, 70, 75, 80, 90],
    "ExamMarks": [35, 40, 45, 50, 55, 60, 65, 70, 80, 90]
})

df

   StudyHours  Attendance  AssignmentMarks  ExamMarks
0           1          50               40         35
1           2          55               45         40
2           3          60               50         45
3           4          65               55         50
4           5          70               60         55
5           6          75               65         60
6           7          80               70         65
7           8          85               75         70
8           9          90               80         80
9          10          95               90         90

In [63]:
X = df[["StudyHours", "Attendance", "AssignmentMarks"]]
y = df["ExamMarks"]

display(X)
display(y)
print(len(x))
print(len(y))
print(x.shape)

   StudyHours  Attendance  AssignmentMarks
0           1          50               40
1           2          55               45
2           3          60               50
3           4          65               55
4           5          70               60
5           6          75               65
6           7          80               70
7           8          85               75
8           9          90               80
9          10          95               90

0    35
1    40
2    45
3    50
4    55
5    60
6    65
7    70
8    80
9    90
Name: ExamMarks, dtype: int64

10
10
(10, 3)

In [64]:
print("X shape:", x.shape)
print("Y shape:", y.shape)

print(x)
print(y)

X shape: (10, 3)
Y shape: (10,)
   StudyHours  Attendance  AssignmentMarks
0           1          50               40
1           2          55               45
2           3          60               50
3           4          65               55
4           5          70               60
5           6          75               65
6           7          80               70
7           8          85               75
8           9          90               80
9          10          95               90
0    35
1    40
2    45
3    50
4    55
5    60
6    65
7    70
8    80
9    90
Name: ExamMarks, dtype: int64

In [65]:
x = df[["StudyHours", "Attendance", "AssignmentMarks"]]
y = df["ExamMarks"]

print("X rows:", len(x))
print("Y rows:", len(y))

X rows: 10
Y rows: 10

In [66]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

print("Training rows:", len(x_train))
print("Testing rows:", len(x_test))

Training rows: 8
Testing rows: 2

In [67]:
model = LinearRegression()
model.fit(x_train,y_train)
print("model created ")

model created

In [68]:
y_pred = model.predict(x_test)
result = pd.DataFrame({
    "studehours":x_test["StudyHours"].values,
    "actual hours":y_test.values,
    "predictmarks":y_pred.round()
})
print(result)

   studehours  actual hours  predictmarks
0           9            80          75.0
1           2            40          40.0

In [69]:
# MAE: Average absolute prediction error. Lower is better.

# R² score: Measures how well the model explains variation in the test data.
# A higher score is generally better, but this tiny dataset is not enough to
# establish real-world accuracy.

print("MAE: ",mean_absolute_error(y_test,y_pred))
print("R2 Score: ",r2_score(y_test,y_pred))

MAE:  2.500000000000007
R2 Score:  0.96875

In [47]:
# MAE Value	  MAE Interpretation	  R² Score	  R² Interpretation
# 0	          Perfect predictions	  1.00	      Perfect fit
# 0–2	      Very small error	      0.90–0.99	  Excellent fit
# 2–5	       Often good	          0.75–0.90	  Good fit
# 5–10	      May be acceptable	      0.50–0.75	  Moderate fit
# Above 10	  May need improvement    0.00–0.50	  Weak fit

# —	—	    Below 0	Worse than predicting the test-set mean

# MAE guidelines assume marks out of 100. These are general guidelines, not strict rules.

In [50]:
new_student = pd.DataFrame({
    "StudyHours": [6],
    "Attendance": [80],
    "AssignmentMarks": [75]
})
new_student

   StudyHours  Attendance  AssignmentMarks
0           6          80               75

In [53]:
prediction = model.predict(new_student)
print("predicted exam marks :",round(prediction[0],2))

predicted exam marks : 75.19

In [82]:
# 3 predict price home 
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error

In [83]:
    # 3
import pandas as pd

df = pd.DataFrame({
    "Area_sqft": [
        500, 600, 700, 800, 900,
        1000, 1100, 1200, 1300, 1400,
        1500, 1600, 1700, 1800, 2000
    ],

    "Bedrooms": [
        1, 1, 2, 2, 2,
        2, 3, 3, 3, 3,
        3, 3, 4, 4, 4
    ],

    "Age_years": [
        20, 18, 15, 12, 10,
        8, 7, 6, 5, 4,
        3, 5, 2, 3, 1
    ],

    "Price_lakhs": [
        15, 18, 22, 26, 30,
        34, 38, 42, 46, 50,
        55, 58, 63, 67, 75
    ]
})

df

    Area_sqft  Bedrooms  Age_years  Price_lakhs
0         500         1         20           15
1         600         1         18           18
2         700         2         15           22
3         800         2         12           26
4         900         2         10           30
5        1000         2          8           34
6        1100         3          7           38
7        1200         3          6           42
8        1300         3          5           46
9        1400         3          4           50
10       1500         3          3           55
11       1600         3          5           58
12       1700         4          2           63
13       1800         4          3           67
14       2000         4          1           75

In [84]:
x = df[["Area_sqft","Bedrooms","Age_years"]]
y = df["Price_lakhs"]
print(x)
print(y)

    Area_sqft  Bedrooms  Age_years
0         500         1         20
1         600         1         18
2         700         2         15
3         800         2         12
4         900         2         10
5        1000         2          8
6        1100         3          7
7        1200         3          6
8        1300         3          5
9        1400         3          4
10       1500         3          3
11       1600         3          5
12       1700         4          2
13       1800         4          3
14       2000         4          1
0     15
1     18
2     22
3     26
4     30
5     34
6     38
7     42
8     46
9     50
10    55
11    58
12    63
13    67
14    75
Name: Price_lakhs, dtype: int64

In [88]:
x_train,x_test,y_train,y_test = train_test_split(
    x,y, test_size=0.2 ,random_state=42
)
print(x_train)
print(x_test)

    Area_sqft  Bedrooms  Age_years
13       1800         4          3
5        1000         2          8
8        1300         3          5
2         700         2         15
1         600         1         18
14       2000         4          1
4         900         2         10
7        1200         3          6
10       1500         3          3
12       1700         4          2
3         800         2         12
6        1100         3          7
    Area_sqft  Bedrooms  Age_years
9        1400         3          4
11       1600         3          5
0         500         1         20

In [89]:
model = LinearRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print(y_pred)

[50.44723969 58.87508735 13.95265549]

In [93]:
result = pd.DataFrame({
    "Ares_sqft":x_test["Area_sqft"].values,
    "Bedrooms":x_test["Bedrooms"].values,
    "Age_years":x_test["Age_years"].values,
    "Actual_price":y_test.values,
    "Predict_price":y_pred
})
result

   Ares_sqft  Bedrooms  Age_years  Actual_price  Predict_price
0       1400         3          4            50      50.447240
1       1600         3          5            58      58.875087
2        500         1         20            15      13.952655

In [103]:
# polynomial regression 
# Polynomial Regression uses PolynomialFeatures as a preprocessing step, then uses LinearRegression to train the model.
# One small clarification: Polynomial Regression is the overall modelling approach, not just the feature itself.

import pandas as pd

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error

df = pd.DataFrame({
        "StudyHours": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                   11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    "Marks": [12, 15, 20, 24, 28, 31, 35, 38, 42, 45,
              49, 53, 58, 64, 70, 77, 85, 94, 104, 115]
})
# df

X = df[["StudyHours"]]
y = df["Marks"]
# print(X)
# print(y)

# split data
X_train,X_test,y_train,y_test = train_test_split(
    X,y, test_size=0.2, random_state=42
)
print(X_train)
print(X_test)

    StudyHours
8            9
5            6
11          12
3            4
18          19
16          17
13          14
2            3
9           10
19          20
4            5
12          13
7            8
10          11
14          15
6            7
    StudyHours
0            1
17          18
15          16
1            2

In [106]:
# polynomial features
# formula is y = b0 + b1(x) + b2(x)square
# degree = 2 is x =2

poly = PolynomialFeatures(degree=2)

# poly.fit(X)
# X_train_poly = poly.transform(X_train)
X_train_poly = poly.fit_transform(X_train)
# print(X_train_poly)
X_test_poly = poly.transform(X_test)
# print(X_test_poly)

[[  1.   1.   1.]
 [  1.  18. 324.]
 [  1.  16. 256.]
 [  1.   2.   4.]]

In [111]:
# create train model
model = LinearRegression()
model.fit(X_train_poly,y_train)

y_pred = model.predict(X_test_poly)

# print(y_pred)
results = pd.DataFrame({
    "Actual Marks": y_test.values,
    "Predicted Marks": y_pred
})

# print(result)

# print("\nModel Evaluation:")
# print("MAE:", mean_absolute_error(y_test, y_pred))
# print("R2 Score:", r2_score(y_test, y_pred))

print("\nActual vs Predicted:")
print(results.round(2))

   Ares_sqft  Bedrooms  Age_years  Actual_price  Predict_price
0       1400         3          4            50      50.447240
1       1600         3          5            58      58.875087
2        500         1         20            15      13.952655

Model Evaluation:
MAE: 5.102112285441029
R2 Score: 0.9710942591354115

Actual vs Predicted:
   Actual Marks  Predicted Marks
0            12            21.66
1            94            94.92
2            77            79.49
3            15            22.33