In [3]:
# polynomial regression 
# Polynomial Regression uses PolynomialFeatures as a preprocessing step, then uses LinearRegression to train the model.
# One small clarification: Polynomial Regression is the overall modelling approach, not just the feature itself.

import pandas as pd

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error

df = pd.DataFrame({
        "StudyHours": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                   11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    "Marks": [12, 15, 20, 24, 28, 31, 35, 38, 42, 45,
              49, 53, 58, 64, 70, 77, 85, 94, 104, 115]
})
df

    StudyHours  Marks
0            1     12
1            2     15
2            3     20
3            4     24
4            5     28
5            6     31
6            7     35
7            8     38
8            9     42
9           10     45
10          11     49
11          12     53
12          13     58
13          14     64
14          15     70
15          16     77
16          17     85
17          18     94
18          19    104
19          20    115

In [4]:
X = df[["StudyHours"]]
y = df["Marks"]

print(X)
print(y)

    StudyHours
0            1
1            2
2            3
3            4
4            5
5            6
6            7
7            8
8            9
9           10
10          11
11          12
12          13
13          14
14          15
15          16
16          17
17          18
18          19
19          20
0      12
1      15
2      20
3      24
4      28
5      31
6      35
7      38
8      42
9      45
10     49
11     53
12     58
13     64
14     70
15     77
16     85
17     94
18    104
19    115
Name: Marks, dtype: int64

In [5]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y, test_size = 0.2, random_state=42
)
print(X_train)
print(X_test)

    StudyHours
8            9
5            6
11          12
3            4
18          19
16          17
13          14
2            3
9           10
19          20
4            5
12          13
7            8
10          11
14          15
6            7
    StudyHours
0            1
17          18
15          16
1            2

In [11]:
# apply polynomial regression
# formula is y = b0 + b1(x) + b2(x)square
# degree = 2 is x =2

poly = PolynomialFeatures(degree=2)

# X_train_poly = poly.fit_transform(X_train)
# X_test_poly = poly.transform(X_test)

poly.fit(X)

X_train_poly = poly.transform(X_train)
X_test_poly = poly.transform(X_test)

print(X_train_poly)
print("break")
print(X_test_poly)

[[  1.   9.  81.]
 [  1.   6.  36.]
 [  1.  12. 144.]
 [  1.   4.  16.]
 [  1.  19. 361.]
 [  1.  17. 289.]
 [  1.  14. 196.]
 [  1.   3.   9.]
 [  1.  10. 100.]
 [  1.  20. 400.]
 [  1.   5.  25.]
 [  1.  13. 169.]
 [  1.   8.  64.]
 [  1.  11. 121.]
 [  1.  15. 225.]
 [  1.   7.  49.]]
break
[[  1.   1.   1.]
 [  1.  18. 324.]
 [  1.  16. 256.]
 [  1.   2.   4.]]

In [14]:
model = LinearRegression()
model.fit(X_train_poly,y_train)

y_pred = model.predict(X_test_poly)
print(y_pred)

[21.65908999 94.9238484  79.49072421 22.33478654]

In [18]:
result = pd.DataFrame({
    "Actual price":y_test.values,
    "predect price":y_pred
})
print(result)

print("R2_score",r2_score(y_test,y_pred))
print("MAE :- ",mean_absolute_error(y_test,y_pred))

print(result.round(2))

   Actual price  predect price
0            12      21.659090
1            94      94.923848
2            77      79.490724
3            15      22.334787
R2_score 0.9710942591354115
MAE :-  5.102112285441029
   Actual price  predect price
0            12          21.66
1            94          94.92
2            77          79.49
3            15          22.33

In [21]:
# multi polynomial regression

import pandas as pd

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error

df = pd.DataFrame({
    "Area_sqft": [
        500, 600, 700, 800, 900,
        1000, 1100, 1200, 1300, 1400,
        1500, 1600, 1700, 1800, 2000
    ],

    "Bedrooms": [
        1, 1, 2, 2, 2,
        3, 3, 3, 3, 4,
        4, 4, 4, 5, 5
    ],

    "Age_years": [
        20, 18, 15, 12, 10,
        9, 8, 7, 6, 5,
        4, 3, 3, 2, 1
    ],

    "Price_lakhs": [
        15, 18, 22, 25, 29,
        35, 39, 44, 48, 55,
        60, 66, 70, 78, 90
    ]
})

df

    Area_sqft  Bedrooms  Age_years  Price_lakhs
0         500         1         20           15
1         600         1         18           18
2         700         2         15           22
3         800         2         12           25
4         900         2         10           29
5        1000         3          9           35
6        1100         3          8           39
7        1200         3          7           44
8        1300         3          6           48
9        1400         4          5           55
10       1500         4          4           60
11       1600         4          3           66
12       1700         4          3           70
13       1800         5          2           78
14       2000         5          1           90

In [22]:
X = df[["Age_years","Bedrooms","Area_sqft"]]
y = df["Price_lakhs"]

print(X)
print(y)

    Age_years  Bedrooms  Area_sqft
0          20         1        500
1          18         1        600
2          15         2        700
3          12         2        800
4          10         2        900
5           9         3       1000
6           8         3       1100
7           7         3       1200
8           6         3       1300
9           5         4       1400
10          4         4       1500
11          3         4       1600
12          3         4       1700
13          2         5       1800
14          1         5       2000
0     15
1     18
2     22
3     25
4     29
5     35
6     39
7     44
8     48
9     55
10    60
11    66
12    70
13    78
14    90
Name: Price_lakhs, dtype: int64

In [23]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y, test_size=0.2, random_state=42
)
print(X_train)
print(X_test)

    Age_years  Bedrooms  Area_sqft
13          2         5       1800
5           9         3       1000
8           6         3       1300
2          15         2        700
1          18         1        600
14          1         5       2000
4          10         2        900
7           7         3       1200
10          4         4       1500
12          3         4       1700
3          12         2        800
6           8         3       1100
    Age_years  Bedrooms  Area_sqft
9           5         4       1400
11          3         4       1600
0          20         1        500

In [29]:
# add polynomial Features

poly = PolynomialFeatures(degree=2)

poly.fit(X)

X_train_poly = poly.transform(X_train)
X_test_poly = poly.transform(X_test)

print(X_train_poly)
print("break")
print(X_test_poly)

[[1.00e+00 2.00e+00 5.00e+00 1.80e+03 4.00e+00 1.00e+01 3.60e+03 2.50e+01
  9.00e+03 3.24e+06]
 [1.00e+00 9.00e+00 3.00e+00 1.00e+03 8.10e+01 2.70e+01 9.00e+03 9.00e+00
  3.00e+03 1.00e+06]
 [1.00e+00 6.00e+00 3.00e+00 1.30e+03 3.60e+01 1.80e+01 7.80e+03 9.00e+00
  3.90e+03 1.69e+06]
 [1.00e+00 1.50e+01 2.00e+00 7.00e+02 2.25e+02 3.00e+01 1.05e+04 4.00e+00
  1.40e+03 4.90e+05]
 [1.00e+00 1.80e+01 1.00e+00 6.00e+02 3.24e+02 1.80e+01 1.08e+04 1.00e+00
  6.00e+02 3.60e+05]
 [1.00e+00 1.00e+00 5.00e+00 2.00e+03 1.00e+00 5.00e+00 2.00e+03 2.50e+01
  1.00e+04 4.00e+06]
 [1.00e+00 1.00e+01 2.00e+00 9.00e+02 1.00e+02 2.00e+01 9.00e+03 4.00e+00
  1.80e+03 8.10e+05]
 [1.00e+00 7.00e+00 3.00e+00 1.20e+03 4.90e+01 2.10e+01 8.40e+03 9.00e+00
  3.60e+03 1.44e+06]
 [1.00e+00 4.00e+00 4.00e+00 1.50e+03 1.60e+01 1.60e+01 6.00e+03 1.60e+01
  6.00e+03 2.25e+06]
 [1.00e+00 3.00e+00 4.00e+00 1.70e+03 9.00e+00 1.20e+01 5.10e+03 1.60e+01
  6.80e+03 2.89e+06]
 [1.00e+00 1.20e+01 2.00e+00 8.00e+02 1.44e+02 2.40e+01 9.60e+03 4.00e+00
  1.60e+03 6.40e+05]
 [1.00e+00 8.00e+00 3.00e+00 1.10e+03 6.40e+01 2.40e+01 8.80e+03 9.00e+00
  3.30e+03 1.21e+06]]
break
[[1.00e+00 5.00e+00 4.00e+00 1.40e+03 2.50e+01 2.00e+01 7.00e+03 1.60e+01
  5.60e+03 1.96e+06]
 [1.00e+00 3.00e+00 4.00e+00 1.60e+03 9.00e+00 1.20e+01 4.80e+03 1.60e+01
  6.40e+03 2.56e+06]
 [1.00e+00 2.00e+01 1.00e+00 5.00e+02 4.00e+02 2.00e+01 1.00e+04 1.00e+00
  5.00e+02 2.50e+05]]

In [35]:
model = LinearRegression()
model.fit(X_train_poly,y_train)

y_pred = model.predict(X_test_poly)

print(y_pred)

result = pd.DataFrame({
    "Actual price":y_test.values,
    "predict proce":y_pred
})

print(result.round(2))

print("MAE:- ",mean_absolute_error(y_test,y_pred))
print("r2_score:- ",r2_score(y_test,y_pred))

[55.01126986 64.54272421 14.17815339]
   Actual price  predict proce
0            55          55.01
1            66          64.54
2            15          14.18
MAE:-  0.7634640880906005
r2_score:-  0.9980570025907918