In [1]:
import pandas as pd
df = pd.read_csv("employees_2.csv")
df

      EmpID          Name  Department   Age   Salary  Experience       City
0         1    Employee_1  Operations  28.0  28278.0          17      Surat
1         2    Employee_2          HR  29.0  38434.0          34  Ahmedabad
2         3    Employee_3   Marketing  48.0  29165.0           1  Ahmedabad
3         4    Employee_4          HR  35.0  91237.0           1     Mumbai
4         5    Employee_5          HR  55.0  79987.0          14     Rajkot
...     ...           ...         ...   ...      ...         ...        ...
1095    437  Employee_437   Marketing  27.0  66827.0          15     Rajkot
1096    765  Employee_765     Finance   NaN  79000.0          35     Rajkot
1097     89   Employee_89          HR   NaN  85332.0          22   Vadodara
1098     64   Employee_64          IT  57.0  57271.0           2     Mumbai
1099    827  Employee_827       Sales  32.0  46910.0          13      Surat

[1100 rows x 7 columns]

In [6]:
import pandas as pd
df = pd.read_csv("employees.csv")
df.sample(4)

       Name  Age  Salary Occup
2  Abhishek   26   49000    AD
0      Aman   20   50000    DS
3    Gautam   28   62000    WD
1     Manav   24   54000    FS

In [9]:
df.describe(include="all")

        Name        Age        Salary Occup
count      7   7.000000      7.000000     7
unique     7        NaN           NaN     4
top     Aman        NaN           NaN    AD
freq       1        NaN           NaN     3
mean     NaN  25.857143  54714.285714   NaN
std      NaN   4.488079   7476.948703   NaN
min      NaN  20.000000  45000.000000   NaN
25%      NaN  22.500000  49500.000000   NaN
50%      NaN  26.000000  54000.000000   NaN
75%      NaN  29.000000  59500.000000   NaN
max      NaN  32.000000  66000.000000   NaN

In [11]:
df.isnull().sum()

Name      0
Age       0
Salary    0
Occup     0
dtype: int64

In [12]:
df = pd.read_csv("employees_2.csv")
df

      EmpID          Name  Department   Age   Salary  Experience       City
0         1    Employee_1  Operations  28.0  28278.0          17      Surat
1         2    Employee_2          HR  29.0  38434.0          34  Ahmedabad
2         3    Employee_3   Marketing  48.0  29165.0           1  Ahmedabad
3         4    Employee_4          HR  35.0  91237.0           1     Mumbai
4         5    Employee_5          HR  55.0  79987.0          14     Rajkot
...     ...           ...         ...   ...      ...         ...        ...
1095    437  Employee_437   Marketing  27.0  66827.0          15     Rajkot
1096    765  Employee_765     Finance   NaN  79000.0          35     Rajkot
1097     89   Employee_89          HR   NaN  85332.0          22   Vadodara
1098     64   Employee_64          IT  57.0  57271.0           2     Mumbai
1099    827  Employee_827       Sales  32.0  46910.0          13      Surat

[1100 rows x 7 columns]

In [15]:
df["City"].unique()

<ArrowStringArray>
['Surat', 'Ahmedabad', 'Mumbai', 'Rajkot', 'Pune', 'Vadodara', nan]
Length: 7, dtype: str

In [23]:
df["Age"].mean()

np.float64(40.09289099526066)

In [29]:
df["City"].mode()
# meaning it finds the most frequently occurring city
# It does not return a simple text string; it returns a pandas Series (a list-like structure).

0    Mumbai
Name: City, dtype: str

In [30]:
df["City"].mode()[0]

'Mumbai'

In [32]:
import seaborn as sns
data = sns.load_dataset("tips")
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]